arm:
  #kinematics_solver: j2s7s300_robot_arm_kinematics/IKFastKinematicsPlugin
  #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005 # is not applicable here(trac_ik)
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3 #parameter is unneeded(trac_ik)
